# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DevChai
email: ohinchang@mail.com
description: Developer C
baseurl: "/dev" # the subpath of your site, e.g. /blog
url: "https://devchai.github.io" # the base hostname & protocol for your site
github_username:  devchai

gems: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
